parameters:
    paypal.client_id: 'AYqdLas5cTEw6F-1btzVuaaS8-YHsvhNr1PAkcijRzhjMArAFu-697i2HN6kwuhvO2RE9L-LImFemwFg'
    paypal.secret: 'EA0n_8Jm9onrBkuYNam9v0kaSDpyFaNmFaFgmZs8SdjI3K1m2xVmJY6J8sy6ONlqr7ZBkafmtGS9fpti'
    paypal.sandbox: true

services:
    _defaults:
        autowire: true      # Injecte automatiquement les dépendances dans vos services
        autoconfigure: true # Enregistre automatiquement vos services comme commandes, abonnés aux événements, etc.

    # Définir les services de l'application
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Service\PayPalService:
        arguments:
            $clientId: '%paypal.client_id%'
            $secret: '%paypal.secret%'
